/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author Unknown User
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }
    
    // Criação de variáveis para a realização de operações aritméticas
    Double valor1, valor2;
    String caracteres[] = new String[2];
    String sinal;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        visor = new javax.swing.JTextField();
        b_sete = new javax.swing.JButton();
        b_oito = new javax.swing.JButton();
        b_nove = new javax.swing.JButton();
        b_quatro = new javax.swing.JButton();
        b_cinco = new javax.swing.JButton();
        b_seis = new javax.swing.JButton();
        b_um = new javax.swing.JButton();
        b_dois = new javax.swing.JButton();
        b_tres = new javax.swing.JButton();
        b_limpa = new javax.swing.JButton();
        b_zero = new javax.swing.JButton();
        b_igual = new javax.swing.JButton();
        b_div = new javax.swing.JButton();
        b_soma = new javax.swing.JButton();
        b_sub = new javax.swing.JButton();
        b_mult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        visor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visorActionPerformed(evt);
            }
        });

        b_sete.setText("7");
        b_sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_seteActionPerformed(evt);
            }
        });

        b_oito.setText("8");
        b_oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_oitoActionPerformed(evt);
            }
        });

        b_nove.setText("9");
        b_nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_noveActionPerformed(evt);
            }
        });

        b_quatro.setText("4");
        b_quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_quatroActionPerformed(evt);
            }
        });

        b_cinco.setText("5");
        b_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cincoActionPerformed(evt);
            }
        });

        b_seis.setText("6");
        b_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_seisActionPerformed(evt);
            }
        });

        b_um.setText("1");
        b_um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_umActionPerformed(evt);
            }
        });

        b_dois.setText("2");
        b_dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_doisActionPerformed(evt);
            }
        });

        b_tres.setText("3");
        b_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tresActionPerformed(evt);
            }
        });

        b_limpa.setText("C");
        b_limpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_limpaActionPerformed(evt);
            }
        });

        b_zero.setText("0");
        b_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_zeroActionPerformed(evt);
            }
        });

        b_igual.setText("=");
        b_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_igualActionPerformed(evt);
            }
        });

        b_div.setText("/");
        b_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_divActionPerformed(evt);
            }
        });

        b_soma.setText("+");
        b_soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_somaActionPerformed(evt);
            }
        });

        b_sub.setText("-");
        b_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_subActionPerformed(evt);
            }
        });

        b_mult.setText("*");
        b_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_multActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b_sete)
                                .addGap(18, 18, 18)
                                .addComponent(b_oito)
                                .addGap(18, 18, 18)
                                .addComponent(b_nove))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b_quatro)
                                .addGap(18, 18, 18)
                                .addComponent(b_cinco)
                                .addGap(18, 18, 18)
                                .addComponent(b_seis))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b_um)
                                .addGap(18, 18, 18)
                                .addComponent(b_dois)
                                .addGap(18, 18, 18)
                                .addComponent(b_tres))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b_limpa)
                                .addGap(18, 18, 18)
                                .addComponent(b_zero)
                                .addGap(18, 18, 18)
                                .addComponent(b_igual)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_div)
                            .addComponent(b_soma)
                            .addComponent(b_sub)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(b_mult)))
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_sete)
                            .addComponent(b_oito)
                            .addComponent(b_nove))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_quatro)
                            .addComponent(b_cinco)
                            .addComponent(b_seis))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_um)
                            .addComponent(b_dois)
                            .addComponent(b_tres))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_limpa)
                            .addComponent(b_zero)
                            .addComponent(b_igual)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b_div)
                        .addGap(18, 18, 18)
                        .addComponent(b_soma)
                        .addGap(18, 18, 18)
                        .addComponent(b_sub)
                        .addGap(18, 18, 18)
                        .addComponent(b_mult)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visorActionPerformed

    private void b_oitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_oitoActionPerformed
        visor.setText(visor.getText() + "8");
    }//GEN-LAST:event_b_oitoActionPerformed

    private void b_quatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_quatroActionPerformed
        visor.setText(visor.getText() + "4");
    }//GEN-LAST:event_b_quatroActionPerformed

    private void b_seteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_seteActionPerformed
        visor.setText(visor.getText() + "7");
    }//GEN-LAST:event_b_seteActionPerformed

    private void b_umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_umActionPerformed
        visor.setText(visor.getText() + "1");
    }//GEN-LAST:event_b_umActionPerformed

    private void b_doisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_doisActionPerformed
        visor.setText(visor.getText() + "2");
    }//GEN-LAST:event_b_doisActionPerformed

    private void b_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tresActionPerformed
        visor.setText(visor.getText() + "3");
    }//GEN-LAST:event_b_tresActionPerformed

    private void b_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cincoActionPerformed
        visor.setText(visor.getText() + "5");
    }//GEN-LAST:event_b_cincoActionPerformed

    private void b_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_seisActionPerformed
        visor.setText(visor.getText() + "6");
    }//GEN-LAST:event_b_seisActionPerformed

    private void b_noveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_noveActionPerformed
        visor.setText(visor.getText() + "9");
    }//GEN-LAST:event_b_noveActionPerformed

    private void b_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_zeroActionPerformed
        visor.setText(visor.getText() + "0");
    }//GEN-LAST:event_b_zeroActionPerformed

    private void b_limpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_limpaActionPerformed
        visor.setText("");
    }//GEN-LAST:event_b_limpaActionPerformed

    private void b_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_divActionPerformed
        // visor.setText(visor.getText() + "/");
        valor1 = Double.parseDouble(visor.getText()); // Recebe o 1° valor no campo de texto da calculadora.
        //visor.setText("");
        sinal = "div";
    }//GEN-LAST:event_b_divActionPerformed

    private void b_somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_somaActionPerformed
        valor1 = Double.parseDouble(visor.getText()); // Recebe o 1° valor no campo de texto da calculadora.
        visor.setText("");
        sinal = "soma";
    }//GEN-LAST:event_b_somaActionPerformed

    private void b_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_subActionPerformed
        // visor.setText(visor.getText() + "-");
        valor1 = Double.parseDouble(visor.getText()); // Recebe o 1° valor no campo de texto da calculadora.
        visor.setText("");
        sinal = "sub";
    }//GEN-LAST:event_b_subActionPerformed

    private void b_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_multActionPerformed
        //visor.setText(visor.getText() + "*");
        valor1 = Double.parseDouble(visor.getText()); // Recebe o 1° valor no campo de texto da calculadora.
        visor.setText("");
        sinal = "mult";
    }//GEN-LAST:event_b_multActionPerformed

    private void b_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_igualActionPerformed
        valor2 = Double.parseDouble(visor.getText()); // Recebe o 2° valor no campo de texto da calculadora.
        if(sinal == "mult"){
            visor.setText(String.valueOf(valor1*valor2)); 
    }
        if(sinal == "sub"){
            visor.setText(String.valueOf(valor1-valor2)); 
    }
        if(sinal == "div"){
            visor.setText(String.valueOf(valor1/valor2)); 
    }
        if(sinal == "soma"){
            visor.setText(String.valueOf(valor1+valor2)); 
    }//GEN-LAST:event_b_igualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cinco;
    private javax.swing.JButton b_div;
    private javax.swing.JButton b_dois;
    private javax.swing.JButton b_igual;
    private javax.swing.JButton b_limpa;
    private javax.swing.JButton b_mult;
    private javax.swing.JButton b_nove;
    private javax.swing.JButton b_oito;
    private javax.swing.JButton b_quatro;
    private javax.swing.JButton b_seis;
    private javax.swing.JButton b_sete;
    private javax.swing.JButton b_soma;
    private javax.swing.JButton b_sub;
    private javax.swing.JButton b_tres;
    private javax.swing.JButton b_um;
    private javax.swing.JButton b_zero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField visor;
    // End of variables declaration//GEN-END:variables
}
